name: Terraform and Conftest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-conftest:
    name: Terraform Plan and Conftest Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Debug: Check for state and plan files
      - name: Check for Terraform State and Plan Files
        run: |
          ls -a || true
          if [ -f "terraform.tfstate" ] || [ -f "terraform.tfstate.backup" ]; then
            echo "Error: Terraform state files found in repository. Please remove them."
            exit 1
          fi
          if [ -f "tfplan" ]; then
            echo "Error: tfplan file found in repository. Please remove it."
            exit 1
          fi

      # Install Conftest
      - name: Install Conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      # Verify tfplan.json exists
      - name: Check for Terraform Plan JSON
        run: |
          if [ ! -f "tfplan.json" ]; then
            echo "Error: tfplan.json not found in repository"
            exit 1
          fi
          echo "Terraform plan JSON found: tfplan.json"

      # Verify Conftest policies exist
      - name: Check for OPA policies
        run: |
          if [ ! -d "policies" ] || [ -z "$(ls -A policies/*.rego 2>/dev/null)" ]; then
            echo "Error: No OPA policy files found in 'policies' directory"
            exit 1
          fi
          echo "OPA policies found:"
          ls -l policies/*.rego

      # Verify Conftest policies
      - name: Verify Conftest Policies
        run: |
          conftest verify -p policies 2> conftest_verify_error.log
          if [ $? -ne 0 ]; then
            echo "Invalid OPA policies detected. Error details:"
            cat conftest_verify_error.log
            exit 1
          fi
          echo "OPA policies verified successfully"

      # Run Conftest tests with detailed output
      - name: Conftest Test with OPA Policies
        run: |
          conftest test tfplan.json -p policies --all-namespaces --trace > conftest_output.log 2> conftest_error.log
          TEST_STATUS=$?
          if [ $TEST_STATUS -ne 0 ]; then
            echo "Conftest policy enforcement failed. Violations found:"
            cat conftest_error.log
            echo "Detailed test output:"
            cat conftest_output.log
            exit 1
          fi
          echo "Conftest policy enforcement passed. No violations found."
          cat conftest_output.log

      # Upload Conftest logs on failure
      - name: Upload Conftest logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: conftest-logs
          path: |
            conftest_output.log
            conftest_error.log