name: Terraform and Conftest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform-conftest:
    name: Conftest Test
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 安装 Conftest
      - name: 安装 Conftest
        run: |
          wget -q https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      # 验证 tfplan.json 是否存在
      - name: 检查 Terraform 计划 JSON
        run: |
          if [ ! -f "tfplan.json" ]; then
            echo "错误：未找到 tfplan.json"
            exit 1
          fi
          echo "找到 Terraform 计划 JSON: tfplan.json"

      # 验证 Conftest 策略是否存在
      - name: 检查 OPA 策略
        run: |
          if [ ! -d "policies" ] || [ -z "$(ls -A policies/*.rego 2>/dev/null)" ]; then
            echo "错误：'policies' 目录中未找到 OPA 策略文件"
            exit 1
          fi
          echo "找到 OPA 策略："
          ls -l policies/*.rego

      # 验证 Conftest 策略
      - name: 验证 Conftest 策略
        run: |
          conftest verify -p policies 2> conftest_verify_error.log
          if [ $? -ne 0 ]; then
            echo "检测到无效的 OPA 策略。错误详情："
            cat conftest_verify_error.log
            exit 1
          fi
          echo "OPA 策略验证成功"

      # 运行 Conftest 测试并输出详细日志
      - name: 使用 OPA 策略运行 Conftest 测试
        run: |
          conftest test tfplan.json -p policies --all-namespaces --trace > conftest_output.log 2> conftest_error.log
          TEST_STATUS=$?
          if [ $TEST_STATUS -ne 0 ]; then
            echo "Conftest 策略执行失败。发现违规："
            cat conftest_error.log
            echo "详细测试输出："
            cat conftest_output.log
            exit 1
          fi
          echo "Conftest 策略执行通过。未发现违规。"
          cat conftest_output.log

      # 失败时上传 Conftest 日志
      - name: 失败时上传 Conftest 日志
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: conftest-logs
          path: |
            conftest_output.log
            conftest_error.log