name: Terraform and Conftest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-conftest:
    name: Terraform Plan and OPA Policy Test
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: "dummy"
      ARM_CLIENT_SECRET: "dummy"
      ARM_SUBSCRIPTION_ID: "00000000-0000-0000-0000-000000000000"
      ARM_TENANT_ID: "00000000-0000-0000-0000-000000000000"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      - name: Install Conftest
        run: |
          curl -LO https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan -no-color

      - name: Convert Plan to JSON
        run: terraform show -json tfplan > tfplan.json

      - name: Run Conftest Policy Tests
        run: conftest test tfplan.json -p policies