name: Terraform and Conftest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-conftest:
    name: Terraform Plan and Conftest Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # install Conftest
      - name: Install Conftest
        run: |
          curl -LO https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/
          conftest --version

      # init Terraform
      - name: Terraform Init
        run: terraform init

      # Setup Terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan -no-color

      # Transform JSON format
      - name: Convert Terraform Plan to JSON
        run: terraform show -json tfplan > tfplan.json

      # Run Conftest tests
      - name: Conftest Test
        run: conftest test tfplan.json -p policies